language: java
jdk :  oraclejdk9
install: ./gradlew clean jar

script: 
 # echo `testing coming soon`
 ./gradlew test

after_success:
 - ./gradlew jacocoTestReport
 - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}' 
before_deploy:
 ./gradlew test jacocoTestCovrageVerification
deploy:
 provider: heroku
 on:
   all_branches: true
 run: echo "WIP"


