language: java
jdk: oraclejdk9
install: "./gradlew clean jar"
services:
- docker
env:
  matrix:
  - COVERAGE=0
  - COVERAGE=0.24
  - COVERAGE=0.25
  - COVERAGE=0.35
  - COVERAGE=0.5
  global:
  - secure: "+Yhuky9G4jZf9vc9Takps/godHRk1A3xH5K8tKaKHkyUnXaF1/PlLiIyX5VjtqmNa6PD5u61ut9dD0NYeHd6zI47OSv/1WzH1BUJqVz6HoD6w7Wq7pc5DVU5+/9XccajODt1e1K8TFmhe9s0A4wabrJN+9zIFlFTzBeSmTmTkwZ5shIJAaHS2NwA9W4Dhlf4g/CKX1OrSt6q1eOy/Eici/+vPc/NnzBKqyci3Q+L8iXpunn4EsbkVvONVbJKGusC2Sntz1C5VJFIPst4vw6aYmjk90Lq2cIgpMOpAq4W9ztAu2Zqns3KbUmjleJ2M9aT+LJqmejdGb8B5AEri/Nx+LaZ6ICradBuXxRtb/roJ9KV6rrdSt1b/nNXlw/7k1F7iFFnlcAtsAGCfX2UHMkA9F7qVmzSHoXE3S9XVVFBN4uER0NvGAXPehFsezVGhJ4mA0MmPI6Wo9GkV+EeNnv9pTPzRm3x9G36fl6veaejFw/Bxbd4W9FGSXWU4IyoGhcVcLzrHxfT4QLsDUmYj8VMwwK6o4ApiBz6em4j+ZVnp4HT7ZRHkwb3BVbntfE4/g9l2tKLtkeVYQMryvcImeKOIP8Kvz+q8684rZrT6Zj/oQVhsMdPGMl8kux/Sd545jLQ6fta+Guujv2bH5gSB0VOnVz8anE/yEQ7osha1wBZ9wA="
  - secure: ZK6K9g/OyClfN5OVf0mg/dJG/zjbXefCuC9HeoYbCCnxl/LZsz9dT1kvIvfQ3U4dYPpg6wQ2WDZvggLqaDmSGf6gKEvkGTAIu3rEcQ0PYMy20vwgTqlX7cxuEN6M1X3Eo/QiGqwfvw35cOeOSPs2vzRNQ2AMWcMqvFfUP94aiObMIGLyhNIzcr8V88RAgxr3HxoaSbVld/37Q4Cj7orukPefn1aH8FekaVaT/ziuJVmwaNT57w2tR4YYqe6cRdwjJ57ZiONbVpkKELsO22CrXZskigylK8yPYfTwpn3CyKY6lsUQiSikbhJe8eUoMEjKlZEvLDG0Hcb1RYpo3NKeLfkb7iSVA1pw4GJlhjZ+kwy1OGQZaV0osk7NA+/EYhtagCY9S/0aN/CvQaoCZwR3EVY/6h9VYd2FBq86wInTcblGsUsVdQPvzqk9gw+Byoq66fTNLtkB4ENlvehlp/R9towKxjtOzcZ5Eive4LNL44NdsSOfoC1vXLsHq2iwERsZpJGgyVMN8sztEOKtz7Yqyl1UWFdSiyb3UNVAXNLlKuHQhzvOzgAan557zJsz/iLt2JxDvfvljCQmpEcUokHGCJgl39jowxYPSM3FKXM10Nt/4o6IeBAeEA1+QP/nn2fURYz6xBIP8W8vUW0mug+28aAqXWyKigCr6S1oK3YFT2Y=
script:
- "./gradlew -p ./monolithic/ui check"
- "./gradlew -p ./monolithic/service/cart check"
- "./gradlew -p ./monolithic/service/user check"
- "./gradlew -p ./monolithic/repository/order check"
- "./gradlew -p ./monolithic/repository/cart check"
- "./gradlew -p ./monolithic/repository/product check"
- "./gradlew -p ./monolithic/repository/user check"
deploy:
  provider: script
  script: bash -c "echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_LOGIN}" --password-stdin"
  on:
    all_branches: true
